import { dcMetadata_4_6 } from './metadata';
export { dcAlternateIdentifiers } from "./alternateIdentifier";
export { dcContributors } from "./contributor";
export { dcCreators } from "./creator";
export { dcDates } from "./date";
export { dcDescriptions } from "./description";
export { dcFormat } from "./format";
export { dcFundingReferences } from "./fundingreference";
export { dcGeoLocations } from "./geoLocation";
export { dcIdentifier } from "./identifier";
export { dcLanguage } from "./language";
export { dcPublicationYear } from "./publicationYear";
export { dcPublisher } from "./publisher";
export { dcRelatedIdentifiers } from "./relatedIdentifier";
export { dcRelatedItem } from "./relatedItem";
export { dcResourceType } from "./resourceType";
export { dcRights } from "./rights";
export { dcSizes } from "./size";
export { dcSubjects } from "./subject";
export { dcTitles } from "./title";
export { dcVersion } from "./version";
export { dcRelatedItems} from "./relatedItem";
export {dcMetadata_4_6} from "./metadata";